packages:
  - apps/*
  - packages/*

# React Native / Expo fonctionnent de façon plus fiable avec des node_modules « à plat »
nodeLinker: hoisted

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  lefthook: true
  prisma: true
  '@biomejs/biome': true
  '@nestjs/core': true
  sharp: true
