/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me/push-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["PushController_register"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/push-tokens/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PushController_forget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GamesController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete: operations["UsersController_deleteMe"];
        options?: never;
        head?: never;
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/me/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_agenda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_myGames"];
        put: operations["UsersController_setMyGames"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/birth-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UsersController_setBirthDate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExploreController_venues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExploreController_venue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExploreController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExploreController_rooms"];
        put?: never;
        post: operations["RoomsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EventsController_register"];
        delete: operations["EventsController_cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WaitlistController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ModerationController_blocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ModerationController_block"];
        post?: never;
        delete: operations["ModerationController_unblock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModerationController_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ModerationController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModerationController_resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RoomsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}/participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RoomsController_join"];
        delete: operations["RoomsController_leave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}/candidates/{userId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RoomsController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}/candidates/{userId}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RoomsController_decline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}/host-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RoomsController_hostAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PushController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PushController_forget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** @enum {string} */
                        database: "up";
                    };
                };
            };
        };
    };
    GamesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        /** @enum {string} */
                        kind: "TCG" | "BOARD_GAME";
                        minPlayers: number;
                        maxPlayers: number;
                        formats: {
                            id: string;
                            slug: string;
                            name: string;
                            minPlayers: number;
                            maxPlayers: number;
                            durationMinutes: number;
                            hasBrackets: boolean;
                        }[];
                    }[];
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        email: string;
                        pseudo: string | null;
                        name: string;
                        hasBirthDate: boolean;
                        /** @enum {string} */
                        role: "PLAYER" | "VENUE_STAFF" | "ADMIN";
                        avatarUrl: string | null;
                        /** @enum {string|null} */
                        avatarStatus: "PENDING" | "APPROVED" | "REJECTED" | null;
                        city: string | null;
                        latitude: number | null;
                        longitude: number | null;
                        searchRadiusKm: number;
                        availability: number[];
                        vibes: ("CHILL" | "COMPETITIVE" | "TEACHER" | "BEGINNER" | "HOMEBREW" | "SOCIAL")[];
                        notificationsOff: ("ROOMS" | "MESSAGES" | "VENUES")[];
                        xp: number;
                        mainKwote: {
                            game: string;
                            format: string;
                            kwote: number;
                        } | null;
                        rankings: {
                            game: {
                                slug: string;
                                name: string;
                            };
                            format: string;
                            kwote: number | null;
                            rankedGames: number;
                            reliabilityPct: number;
                        }[];
                        venues: {
                            id: string;
                            slug: string;
                            name: string;
                            /** @enum {string} */
                            role: "MANAGER" | "STAFF";
                        }[];
                    };
                };
            };
        };
    };
    UsersController_deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pseudo?: string;
                    name?: string;
                    city?: string | null;
                    latitude?: number | null;
                    longitude?: number | null;
                    searchRadiusKm?: number;
                    availability?: number[];
                    vibes?: ("CHILL" | "COMPETITIVE" | "TEACHER" | "BEGINNER" | "HOMEBREW" | "SOCIAL")[];
                    notificationsOff?: ("ROOMS" | "MESSAGES" | "VENUES")[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        email: string;
                        pseudo: string | null;
                        name: string;
                        hasBirthDate: boolean;
                        /** @enum {string} */
                        role: "PLAYER" | "VENUE_STAFF" | "ADMIN";
                        avatarUrl: string | null;
                        /** @enum {string|null} */
                        avatarStatus: "PENDING" | "APPROVED" | "REJECTED" | null;
                        city: string | null;
                        latitude: number | null;
                        longitude: number | null;
                        searchRadiusKm: number;
                        availability: number[];
                        vibes: ("CHILL" | "COMPETITIVE" | "TEACHER" | "BEGINNER" | "HOMEBREW" | "SOCIAL")[];
                        notificationsOff: ("ROOMS" | "MESSAGES" | "VENUES")[];
                        xp: number;
                        mainKwote: {
                            game: string;
                            format: string;
                            kwote: number;
                        } | null;
                        rankings: {
                            game: {
                                slug: string;
                                name: string;
                            };
                            format: string;
                            kwote: number | null;
                            rankedGames: number;
                            reliabilityPct: number;
                        }[];
                        venues: {
                            id: string;
                            slug: string;
                            name: string;
                            /** @enum {string} */
                            role: "MANAGER" | "STAFF";
                        }[];
                    };
                };
            };
        };
    };
    UsersController_agenda: {
        parameters: {
            query?: {
                period?: "upcoming" | "past";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        kind: "EVENT" | "ROOM";
                        /** @enum {string|null} */
                        eventType: "GAME_NIGHT" | "INITIATION" | "TOURNAMENT" | "PRERELEASE" | "THEMED" | null;
                        /** @enum {string|null} */
                        roomMode: "RANKED" | "CASUAL" | null;
                        title: string;
                        game: {
                            slug: string;
                            name: string;
                        } | null;
                        place: string | null;
                        /** Format: date-time */
                        startsAt: string;
                        playerCount: number;
                        capacity: number | null;
                        /** @enum {string} */
                        status: "REGISTERED" | "WAITLISTED" | "PENDING" | "MISSING_PLAYERS" | "FULL" | "PLAYED";
                    }[];
                };
            };
        };
    };
    UsersController_myGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        gameIds: string[];
                        formats: {
                            formatId: string;
                            /** @enum {string} */
                            declaredLevel: "BEGINNER" | "INTERMEDIATE" | "CONFIRMED" | "EXPERT";
                        }[];
                    };
                };
            };
        };
    };
    UsersController_setMyGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    gameIds: string[];
                    formats: {
                        formatId: string;
                        /** @enum {string} */
                        declaredLevel: "BEGINNER" | "INTERMEDIATE" | "CONFIRMED" | "EXPERT";
                    }[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        gameIds: string[];
                        formats: {
                            formatId: string;
                            /** @enum {string} */
                            declaredLevel: "BEGINNER" | "INTERMEDIATE" | "CONFIRMED" | "EXPERT";
                        }[];
                    };
                };
            };
        };
    };
    UsersController_setBirthDate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    birthDate: string;
                };
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExploreController_venues: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radiusKm?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        /** @enum {string} */
                        type: "GAME_BAR" | "TCG_SHOP" | "LUDOTHEQUE" | "ASSOCIATION" | "OTHER";
                        address: string;
                        latitude: number;
                        longitude: number;
                        isPartner: boolean;
                        kwatroPerk: string | null;
                        distanceMeters: number;
                        openNow: boolean | null;
                        closesAtMinute: number | null;
                        upcomingEventCount: number;
                    }[];
                };
            };
        };
    };
    ExploreController_venue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        /** @enum {string} */
                        type: "GAME_BAR" | "TCG_SHOP" | "LUDOTHEQUE" | "ASSOCIATION" | "OTHER";
                        address: string;
                        latitude: number;
                        longitude: number;
                        isPartner: boolean;
                        kwatroPerk: string | null;
                        openNow: boolean | null;
                        closesAtMinute: number | null;
                        city: string;
                        quarter: string | null;
                        description: string | null;
                        playFeeCents: number | null;
                        minSpendCents: number | null;
                        acceptsUnaccompaniedMinors: boolean;
                        phone: string | null;
                        website: string | null;
                        transitInfo: string | null;
                        nextOpening: {
                            /** Format: date */
                            date: string;
                            minute: number;
                        } | null;
                        photos: {
                            url: string;
                            caption: string | null;
                        }[];
                        openingHours: {
                            weekday: number;
                            opensAtMinute: number;
                            closesAtMinute: number;
                        }[];
                        closures: {
                            /** Format: date */
                            startsOn: string;
                            /** Format: date */
                            endsOn: string;
                            /** @enum {string} */
                            kind: "CLOSED" | "SPECIAL_HOURS";
                            label: string;
                            note: string | null;
                            opensAtMinute: number | null;
                            closesAtMinute: number | null;
                        }[];
                        accessibility: {
                            label: string;
                            /** @enum {string} */
                            status: "YES" | "NO" | "INFO";
                            note?: string | null;
                        }[];
                        games: {
                            slug: string;
                            name: string;
                            /** @enum {string} */
                            kind: "TCG" | "BOARD_GAME";
                        }[];
                        tcgNote: string | null;
                        boardGames: string[];
                        boardGameCount: number | null;
                        boardGameNote: string | null;
                        events: {
                            id: string;
                            title: string;
                            /** @enum {string} */
                            type: "GAME_NIGHT" | "INITIATION" | "TOURNAMENT" | "PRERELEASE" | "THEMED";
                            /** Format: date-time */
                            startsAt: string;
                            priceCents: number | null;
                            capacity: number | null;
                            registeredCount: number;
                            /** @enum {string} */
                            registrationMode: "NONE" | "IN_APP" | "EXTERNAL";
                            games: {
                                slug: string;
                                name: string;
                            }[];
                            seriesId: string | null;
                            externalUrl: string | null;
                        }[];
                        rooms: {
                            id: string;
                            /** @enum {string} */
                            mode: "RANKED" | "CASUAL";
                            /** Format: date-time */
                            startsAt: string;
                            capacity: number;
                            game: {
                                slug: string;
                                name: string;
                            };
                            format: string | null;
                            bracket: number | null;
                            players: {
                                initial: string;
                            }[];
                            kwoteRange: {
                                min: number;
                                max: number;
                            } | null;
                        }[];
                    };
                };
            };
        };
    };
    ExploreController_events: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radiusKm?: number;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title: string;
                        /** @enum {string} */
                        type: "GAME_NIGHT" | "INITIATION" | "TOURNAMENT" | "PRERELEASE" | "THEMED";
                        /** Format: date-time */
                        startsAt: string;
                        priceCents: number | null;
                        capacity: number | null;
                        registeredCount: number;
                        /** @enum {string} */
                        registrationMode: "NONE" | "IN_APP" | "EXTERNAL";
                        games: {
                            slug: string;
                            name: string;
                        }[];
                        venue: {
                            id: string;
                            slug: string;
                            name: string;
                            isPartner: boolean;
                            distanceMeters: number;
                        };
                    }[];
                };
            };
        };
    };
    ExploreController_rooms: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radiusKm?: number;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        mode: "RANKED" | "CASUAL";
                        /** Format: date-time */
                        startsAt: string;
                        capacity: number;
                        game: {
                            slug: string;
                            name: string;
                        };
                        format: string | null;
                        bracket: number | null;
                        venue: {
                            id: string;
                            name: string;
                            isPartner: boolean;
                            distanceMeters: number;
                        };
                        players: {
                            initial: string;
                        }[];
                        kwoteRange: {
                            min: number;
                            max: number;
                        } | null;
                    }[];
                };
            };
        };
    };
    RoomsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    gameId: string;
                    formatId?: string | null;
                    /** @enum {string} */
                    mode: "RANKED" | "CASUAL";
                    venueId: string;
                    /** Format: date-time */
                    startsAt: string;
                    capacity: number;
                    bracket?: number | null;
                    /** @default false */
                    minorsAllowed?: boolean;
                    /** @default false */
                    autoAccept?: boolean;
                    description?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
        };
    };
    EventsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title: string;
                        /** @enum {string} */
                        type: "GAME_NIGHT" | "INITIATION" | "TOURNAMENT" | "PRERELEASE" | "THEMED";
                        description: string | null;
                        /** Format: date-time */
                        startsAt: string;
                        /** Format: date-time */
                        endsAt: string | null;
                        /** Format: date-time */
                        cancelledAt: string | null;
                        priceCents: number | null;
                        capacity: number | null;
                        minAge: number | null;
                        /** @enum {string} */
                        registrationMode: "NONE" | "IN_APP" | "EXTERNAL";
                        externalUrl: string | null;
                        registeredCount: number;
                        games: {
                            slug: string;
                            name: string;
                        }[];
                        venue: {
                            id: string;
                            slug: string;
                            name: string;
                            address: string;
                            isPartner: boolean;
                        };
                        /** @enum {string|null} */
                        myRegistration: "REGISTERED" | "WAITLISTED" | null;
                    };
                };
            };
        };
    };
    EventsController_register: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title: string;
                        /** @enum {string} */
                        type: "GAME_NIGHT" | "INITIATION" | "TOURNAMENT" | "PRERELEASE" | "THEMED";
                        description: string | null;
                        /** Format: date-time */
                        startsAt: string;
                        /** Format: date-time */
                        endsAt: string | null;
                        /** Format: date-time */
                        cancelledAt: string | null;
                        priceCents: number | null;
                        capacity: number | null;
                        minAge: number | null;
                        /** @enum {string} */
                        registrationMode: "NONE" | "IN_APP" | "EXTERNAL";
                        externalUrl: string | null;
                        registeredCount: number;
                        games: {
                            slug: string;
                            name: string;
                        }[];
                        venue: {
                            id: string;
                            slug: string;
                            name: string;
                            address: string;
                            isPartner: boolean;
                        };
                        /** @enum {string|null} */
                        myRegistration: "REGISTERED" | "WAITLISTED" | null;
                    };
                };
            };
        };
    };
    EventsController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title: string;
                        /** @enum {string} */
                        type: "GAME_NIGHT" | "INITIATION" | "TOURNAMENT" | "PRERELEASE" | "THEMED";
                        description: string | null;
                        /** Format: date-time */
                        startsAt: string;
                        /** Format: date-time */
                        endsAt: string | null;
                        /** Format: date-time */
                        cancelledAt: string | null;
                        priceCents: number | null;
                        capacity: number | null;
                        minAge: number | null;
                        /** @enum {string} */
                        registrationMode: "NONE" | "IN_APP" | "EXTERNAL";
                        externalUrl: string | null;
                        registeredCount: number;
                        games: {
                            slug: string;
                            name: string;
                        }[];
                        venue: {
                            id: string;
                            slug: string;
                            name: string;
                            address: string;
                            isPartner: boolean;
                        };
                        /** @enum {string|null} */
                        myRegistration: "REGISTERED" | "WAITLISTED" | null;
                    };
                };
            };
        };
    };
    WaitlistController_join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    city?: string;
                    /** @enum {boolean} */
                    digitalMajority: true;
                };
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModerationController_blocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        pseudo: string | null;
                        /** Format: date-time */
                        blockedAt: string;
                    }[];
                };
            };
        };
    };
    ModerationController_block: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModerationController_unblock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModerationController_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    reason: "HARASSMENT" | "INAPPROPRIATE_CONTENT" | "CHEATING" | "NO_SHOW" | "MINOR_SAFETY" | "OTHER";
                    /** @default  */
                    details?: string;
                };
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModerationController_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        reason: "HARASSMENT" | "INAPPROPRIATE_CONTENT" | "CHEATING" | "NO_SHOW" | "MINOR_SAFETY" | "OTHER";
                        details: string;
                        /** Format: date-time */
                        createdAt: string;
                        reporter: {
                            id: string;
                            pseudo: string | null;
                        };
                        target: {
                            id: string;
                            pseudo: string | null;
                            minor: boolean;
                            openReports: number;
                        };
                    }[];
                };
            };
        };
    };
    ModerationController_resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoomsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        mode: "RANKED" | "CASUAL";
                        /** @enum {string} */
                        status: "OPEN" | "FULL" | "CONFIRMED" | "IN_PROGRESS" | "FINISHED" | "CANCELLED";
                        /** Format: date-time */
                        startsAt: string;
                        capacity: number;
                        description: string | null;
                        minorsAllowed: boolean;
                        autoAccept: boolean;
                        game: {
                            slug: string;
                            name: string;
                        };
                        format: string | null;
                        bracket: number | null;
                        venue: {
                            id: string;
                            slug: string;
                            name: string;
                            address: string;
                            isPartner: boolean;
                        } | null;
                        host: {
                            pseudo: string | null;
                        };
                        players: {
                            initial: string;
                            pseudo: string | null;
                            userId: string | null;
                        }[];
                        waitlistCount: number;
                        /** @enum {string|null} */
                        myStatus: "PENDING" | "ACCEPTED" | "WAITLISTED" | "DECLINED" | "LEFT" | null;
                        isHost: boolean;
                        candidates: {
                            userId: string;
                            pseudo: string | null;
                            /** @enum {string} */
                            status: "PENDING" | "WAITLISTED";
                            minor: boolean;
                            xp: number;
                            kwote: number | null;
                            rankedGames: number;
                            /** Format: date-time */
                            appliedAt: string;
                        }[];
                    };
                };
            };
        };
    };
    RoomsController_join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        mode: "RANKED" | "CASUAL";
                        /** @enum {string} */
                        status: "OPEN" | "FULL" | "CONFIRMED" | "IN_PROGRESS" | "FINISHED" | "CANCELLED";
                        /** Format: date-time */
                        startsAt: string;
                        capacity: number;
                        description: string | null;
                        minorsAllowed: boolean;
                        autoAccept: boolean;
                        game: {
                            slug: string;
                            name: string;
                        };
                        format: string | null;
                        bracket: number | null;
                        venue: {
                            id: string;
                            slug: string;
                            name: string;
                            address: string;
                            isPartner: boolean;
                        } | null;
                        host: {
                            pseudo: string | null;
                        };
                        players: {
                            initial: string;
                            pseudo: string | null;
                            userId: string | null;
                        }[];
                        waitlistCount: number;
                        /** @enum {string|null} */
                        myStatus: "PENDING" | "ACCEPTED" | "WAITLISTED" | "DECLINED" | "LEFT" | null;
                        isHost: boolean;
                        candidates: {
                            userId: string;
                            pseudo: string | null;
                            /** @enum {string} */
                            status: "PENDING" | "WAITLISTED";
                            minor: boolean;
                            xp: number;
                            kwote: number | null;
                            rankedGames: number;
                            /** Format: date-time */
                            appliedAt: string;
                        }[];
                    };
                };
            };
        };
    };
    RoomsController_leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        mode: "RANKED" | "CASUAL";
                        /** @enum {string} */
                        status: "OPEN" | "FULL" | "CONFIRMED" | "IN_PROGRESS" | "FINISHED" | "CANCELLED";
                        /** Format: date-time */
                        startsAt: string;
                        capacity: number;
                        description: string | null;
                        minorsAllowed: boolean;
                        autoAccept: boolean;
                        game: {
                            slug: string;
                            name: string;
                        };
                        format: string | null;
                        bracket: number | null;
                        venue: {
                            id: string;
                            slug: string;
                            name: string;
                            address: string;
                            isPartner: boolean;
                        } | null;
                        host: {
                            pseudo: string | null;
                        };
                        players: {
                            initial: string;
                            pseudo: string | null;
                            userId: string | null;
                        }[];
                        waitlistCount: number;
                        /** @enum {string|null} */
                        myStatus: "PENDING" | "ACCEPTED" | "WAITLISTED" | "DECLINED" | "LEFT" | null;
                        isHost: boolean;
                        candidates: {
                            userId: string;
                            pseudo: string | null;
                            /** @enum {string} */
                            status: "PENDING" | "WAITLISTED";
                            minor: boolean;
                            xp: number;
                            kwote: number | null;
                            rankedGames: number;
                            /** Format: date-time */
                            appliedAt: string;
                        }[];
                    };
                };
            };
        };
    };
    RoomsController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        mode: "RANKED" | "CASUAL";
                        /** @enum {string} */
                        status: "OPEN" | "FULL" | "CONFIRMED" | "IN_PROGRESS" | "FINISHED" | "CANCELLED";
                        /** Format: date-time */
                        startsAt: string;
                        capacity: number;
                        description: string | null;
                        minorsAllowed: boolean;
                        autoAccept: boolean;
                        game: {
                            slug: string;
                            name: string;
                        };
                        format: string | null;
                        bracket: number | null;
                        venue: {
                            id: string;
                            slug: string;
                            name: string;
                            address: string;
                            isPartner: boolean;
                        } | null;
                        host: {
                            pseudo: string | null;
                        };
                        players: {
                            initial: string;
                            pseudo: string | null;
                            userId: string | null;
                        }[];
                        waitlistCount: number;
                        /** @enum {string|null} */
                        myStatus: "PENDING" | "ACCEPTED" | "WAITLISTED" | "DECLINED" | "LEFT" | null;
                        isHost: boolean;
                        candidates: {
                            userId: string;
                            pseudo: string | null;
                            /** @enum {string} */
                            status: "PENDING" | "WAITLISTED";
                            minor: boolean;
                            xp: number;
                            kwote: number | null;
                            rankedGames: number;
                            /** Format: date-time */
                            appliedAt: string;
                        }[];
                    };
                };
            };
        };
    };
    RoomsController_decline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        mode: "RANKED" | "CASUAL";
                        /** @enum {string} */
                        status: "OPEN" | "FULL" | "CONFIRMED" | "IN_PROGRESS" | "FINISHED" | "CANCELLED";
                        /** Format: date-time */
                        startsAt: string;
                        capacity: number;
                        description: string | null;
                        minorsAllowed: boolean;
                        autoAccept: boolean;
                        game: {
                            slug: string;
                            name: string;
                        };
                        format: string | null;
                        bracket: number | null;
                        venue: {
                            id: string;
                            slug: string;
                            name: string;
                            address: string;
                            isPartner: boolean;
                        } | null;
                        host: {
                            pseudo: string | null;
                        };
                        players: {
                            initial: string;
                            pseudo: string | null;
                            userId: string | null;
                        }[];
                        waitlistCount: number;
                        /** @enum {string|null} */
                        myStatus: "PENDING" | "ACCEPTED" | "WAITLISTED" | "DECLINED" | "LEFT" | null;
                        isHost: boolean;
                        candidates: {
                            userId: string;
                            pseudo: string | null;
                            /** @enum {string} */
                            status: "PENDING" | "WAITLISTED";
                            minor: boolean;
                            xp: number;
                            kwote: number | null;
                            rankedGames: number;
                            /** Format: date-time */
                            appliedAt: string;
                        }[];
                    };
                };
            };
        };
    };
    RoomsController_hostAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    type: "remove";
                    userId: string;
                } | {
                    /** @enum {string} */
                    type: "transfer";
                    userId: string;
                } | {
                    /** @enum {string} */
                    type: "close";
                } | {
                    /** @enum {string} */
                    type: "reopen";
                } | {
                    /** @enum {string} */
                    type: "cancel";
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        mode: "RANKED" | "CASUAL";
                        /** @enum {string} */
                        status: "OPEN" | "FULL" | "CONFIRMED" | "IN_PROGRESS" | "FINISHED" | "CANCELLED";
                        /** Format: date-time */
                        startsAt: string;
                        capacity: number;
                        description: string | null;
                        minorsAllowed: boolean;
                        autoAccept: boolean;
                        game: {
                            slug: string;
                            name: string;
                        };
                        format: string | null;
                        bracket: number | null;
                        venue: {
                            id: string;
                            slug: string;
                            name: string;
                            address: string;
                            isPartner: boolean;
                        } | null;
                        host: {
                            pseudo: string | null;
                        };
                        players: {
                            initial: string;
                            pseudo: string | null;
                            userId: string | null;
                        }[];
                        waitlistCount: number;
                        /** @enum {string|null} */
                        myStatus: "PENDING" | "ACCEPTED" | "WAITLISTED" | "DECLINED" | "LEFT" | null;
                        isHost: boolean;
                        candidates: {
                            userId: string;
                            pseudo: string | null;
                            /** @enum {string} */
                            status: "PENDING" | "WAITLISTED";
                            minor: boolean;
                            xp: number;
                            kwote: number | null;
                            rankedGames: number;
                            /** Format: date-time */
                            appliedAt: string;
                        }[];
                    };
                };
            };
        };
    };
}
